import { ROLES } from './roles';
import { PERM_CAPABILITIES } from './permissions.actions';

const ROLE_PERMISSIONS = {
  [ROLES.OWNER]: [
    PERM_CAPABILITIES.MANAGE_TOURNAMENT, 
    PERM_CAPABILITIES.MANAGE_MATCH, 
    PERM_CAPABILITIES.VIEW_ADMIN_DASHBOARD, 
    PERM_CAPABILITIES.EDIT_ROSTER,
    PERM_CAPABILITIES.VIEW_HIDDEN_DATA
  ],
  [ROLES.ADMIN]: [
    PERM_CAPABILITIES.MANAGE_TOURNAMENT, 
    PERM_CAPABILITIES.MANAGE_MATCH, 
    PERM_CAPABILITIES.VIEW_ADMIN_DASHBOARD,
    PERM_CAPABILITIES.VIEW_HIDDEN_DATA
  ],
  [ROLES.REFEREE]: [
    PERM_CAPABILITIES.MANAGE_MATCH, 
    PERM_CAPABILITIES.VIEW_ADMIN_DASHBOARD
  ],
  [ROLES.CAPTAIN]: [
    PERM_CAPABILITIES.EDIT_ROSTER
  ]
};

export const can = (role, permission) => {
  const allowed = ROLE_PERMISSIONS[role] || [];
  return allowed.includes(permission);
};
