// A central registry of all action names to prevent typos
export const PERM_CAPABILITIES = {
  MANAGE_TOURNAMENT: 'MANAGE_TOURNAMENT',
  MANAGE_MATCH: 'MANAGE_MATCH',
  VIEW_ADMIN_DASHBOARD: 'VIEW_ADMIN_DASHBOARD',
  EDIT_ROSTER: 'EDIT_ROSTER',
  VIEW_HIDDEN_DATA: 'VIEW_HIDDEN_DATA'
};
