import { ROLES } from './roles';

export const PERMISSIONS = {
  MANAGE_TOURNAMENT: 'MANAGE_TOURNAMENT',
  MANAGE_MATCH: 'MANAGE_MATCH',
  VIEW_ADMIN_DASHBOARD: 'VIEW_ADMIN_DASHBOARD',
  EDIT_ROSTER: 'EDIT_ROSTER'
};

const ROLE_PERMISSIONS = {
  [ROLES.OWNER]: [PERMISSIONS.MANAGE_TOURNAMENT, PERMISSIONS.MANAGE_MATCH, PERMISSIONS.VIEW_ADMIN_DASHBOARD, PERMISSIONS.EDIT_ROSTER],
  [ROLES.ADMIN]: [PERMISSIONS.MANAGE_TOURNAMENT, PERMISSIONS.MANAGE_MATCH, PERMISSIONS.VIEW_ADMIN_DASHBOARD],
  [ROLES.REFEREE]: [PERMISSIONS.MANAGE_MATCH, PERMISSIONS.VIEW_ADMIN_DASHBOARD],
  [ROLES.CAPTAIN]: [PERMISSIONS.EDIT_ROSTER]
};

export const can = (role, permission) => {
  const allowed = ROLE_PERMISSIONS[role] || [];
  return allowed.includes(permission);
};
